"""
Генератор x86-64 assembly (NASM, Linux System V ABI).

На входе — список IR-инструкций.
На выходе — текст asm-файла.

Упрощения:
    - только int (float отложен)
    - все переменные на стеке
    - максимум 6 аргументов у функций
    - без оптимизаций
"""

from ..ir import (
    IRAssign, IRBinOp, IRUnaryOp,
    IRLabel, IRJump, IRJumpIfFalse,
    IRFuncBegin, IRCall, IRReturn, IRParam,
)
from .abi import ARG_REGISTERS, RETURN_REGISTER, FRAME_POINTER, STACK_POINTER
from .stack_frame import StackFrame


class X86Generator:
    def __init__(self, instructions):
        self.instructions = instructions
        # строки asm
        self.lines = []
        # текущий стековый фрейм
        self.frame = None
        # имя текущей функции
        self.current_func = None
        # счётчик временных меток (для &&, || и т.п.)
        self.label_counter = 0

    # ----------------------------------------------------------
    # вспомогательные методы
    # ----------------------------------------------------------

    def _emit(self, line):
        """Добавить строку asm."""
        self.lines.append(line)

    def _new_label(self):
        """Сгенерировать уникальную метку для внутренних нужд."""
        self.label_counter += 1
        return f"_L{self.label_counter}"

    def _is_number(self, s):
        """Проверить, что строка — число (int)."""
        try:
            int(s)
            return True
        except ValueError:
            return False

    def _is_float(self, s):
        """Проверить, что строка — float."""
        try:
            float(s)
            return "." in str(s)
        except ValueError:
            return False

    def _load_to_reg(self, reg, value):
        """
        Загрузить значение в регистр.
        value может быть числом или именем переменной.
        """
        if self._is_number(value):
            self._emit(f"    mov {reg}, {value}")
        else:
            offset = self.frame.get_offset(value)
            if offset is None:
                # переменная не размещена — размещаем на лету
                offset = self.frame.allocate(value)
            self._emit(f"    mov {reg}, [{FRAME_POINTER}{offset}]")

    def _store_from_reg(self, reg, name):
        """Сохранить регистр в переменную на стеке."""
        offset = self.frame.get_offset(name)
        if offset is None:
            offset = self.frame.allocate(name)
        self._emit(f"    mov [{FRAME_POINTER}{offset}], {reg}")

    # ----------------------------------------------------------
    # точка входа
    # ----------------------------------------------------------

    def generate(self):
        """Сгенерировать asm для всех инструкций."""
        # шапка файла
        self._emit("; generated by mini-cc")
        self._emit("section .text")

        for instr in self.instructions:
            self._gen_instr(instr)

        # в конце — заглушка для выхода (для Linux)
        self._emit("")
        self._emit("; exit program")
        self._emit("    mov rax, 60        ; sys_exit")
        self._emit("    xor rdi, rdi       ; exit code 0")
        self._emit("    syscall")

        return "\n".join(self.lines)

    # ----------------------------------------------------------
    # диспетчер
    # ----------------------------------------------------------

    def _gen_instr(self, instr):
        """Сгенерировать asm для одной IR-инструкции."""

        if isinstance(instr, IRFuncBegin):
            self._gen_func_begin(instr)

        elif isinstance(instr, IRParam):
            self._gen_param(instr)

        elif isinstance(instr, IRAssign):
            self._gen_assign(instr)

        elif isinstance(instr, IRBinOp):
            self._gen_binop(instr)

        elif isinstance(instr, IRUnaryOp):
            self._gen_unaryop(instr)

        elif isinstance(instr, IRLabel):
            self._gen_label(instr)

        elif isinstance(instr, IRJump):
            self._gen_jump(instr)

        elif isinstance(instr, IRJumpIfFalse):
            self._gen_jump_if_false(instr)

        elif isinstance(instr, IRCall):
            self._gen_call(instr)

        elif isinstance(instr, IRReturn):
            self._gen_return(instr)

        else:
            raise ValueError(f"unknown IR instruction: {type(instr).__name__}")

    # ----------------------------------------------------------
    # функции
    # ----------------------------------------------------------

    def _gen_func_begin(self, instr):
        """Начало функции: prologue."""
        self.current_func = instr.name
        self.frame = StackFrame()

        self._emit("")
        self._emit(f"global {instr.name}")
        self._emit(f"{instr.name}:")
        self._emit(f"    push {FRAME_POINTER}")
        self._emit(f"    mov {FRAME_POINTER}, {STACK_POINTER}")
        # sub rsp сделаем позже — когда узнаем размер фрейма.
        # Пока запишем placeholder-строку, потом заменим.
        self._emit("    ; SUBS_RSP_PLACEHOLDER")

    def _gen_param(self, instr):
        """
        Параметр функции.
        На входе аргумент в регистре (rdi, rsi, ...).
        Сохраняем в локальную переменную на стеке.
        """
        # какой это параметр по счёту?
        param_index = len(self.frame.offsets)
        if param_index >= len(ARG_REGISTERS):
            raise ValueError(
                f"too many parameters (max {len(ARG_REGISTERS)})"
            )
        reg = ARG_REGISTERS[param_index]
        # сохраняем регистр в локальную переменную
        self._store_from_reg(reg, instr.name)

    def _gen_return(self, instr):
        """Return — кладём значение в rax и делаем epilogue."""
        if instr.value is not None:
            self._load_to_reg(RETURN_REGISTER, instr.value)

        # epilogue
        self._emit(f"    mov {STACK_POINTER}, {FRAME_POINTER}")
        self._emit(f"    pop {FRAME_POINTER}")
        self._emit("    ret")

        # заменяем placeholder на реальный sub rsp
        total = self.frame.total_size()
        for i, line in enumerate(self.lines):
            if line == "    ; SUBS_RSP_PLACEHOLDER":
                self.lines[i] = f"    sub {STACK_POINTER}, {total}"
                break

    # ----------------------------------------------------------
    # присваивание
    # ----------------------------------------------------------

    def _gen_assign(self, instr):
        """dest = src."""
        self._load_to_reg("rax", instr.src)
        self._store_from_reg("rax", instr.dest)

    # ----------------------------------------------------------
    # бинарные операции
    # ----------------------------------------------------------

    def _gen_binop(self, instr):
        """dest = left op right."""
        op = instr.op

        # сначала загружаем левый операнд в rax, правый в rcx
        self._load_to_reg("rax", instr.left)
        self._load_to_reg("rcx", instr.right)

        if op == "+":
            self._emit("    add rax, rcx")
        elif op == "-":
            self._emit("    sub rax, rcx")
        elif op == "*":
            self._emit("    imul rax, rcx")
        elif op == "/":
            # idiv требует rdx:rax, обнуляем rdx через cqo
            self._emit("    cqo")
            self._emit("    idiv rcx")
        elif op == "%":
            self._emit("    cqo")
            self._emit("    idiv rcx")
            # остаток в rdx
            self._emit("    mov rax, rdx")
        elif op in ("==", "!=", "<", "<=", ">", ">="):
            self._emit("    cmp rax, rcx")
            setcc = {
                "==": "sete",
                "!=": "setne",
                "<":  "setl",
                "<=": "setle",
                ">":  "setg",
                ">=": "setge",
            }[op]
            self._emit(f"    {setcc} al")
            self._emit("    movzx rax, al")
        elif op in ("&&", "||"):
            # логические операции — через метки
            self._gen_logical(op, instr)
            return
        else:
            raise ValueError(f"unknown binop: {op}")

        self._store_from_reg("rax", instr.dest)

    def _gen_logical(self, op, instr):
        """&& и || через условные переходы."""
        end_label = self._new_label()
        short_label = self._new_label()

        if op == "&&":
            # если left == 0 → результат 0, иначе смотрим right
            self._load_to_reg("rax", instr.left)
            self._emit("    test rax, rax")
            self._emit(f"    jz {short_label}")
            self._load_to_reg("rax", instr.right)
            self._emit("    test rax, rax")
            self._emit(f"    jz {short_label}")
            self._emit("    mov rax, 1")
            self._emit(f"    jmp {end_label}")
            self._emit(f"{short_label}:")
            self._emit("    mov rax, 0")
            self._emit(f"{end_label}:")
        else:  # ||
            self._load_to_reg("rax", instr.left)
            self._emit("    test rax, rax")
            self._emit(f"    jnz {short_label}")
            self._load_to_reg("rax", instr.right)
            self._emit("    test rax, rax")
            self._emit(f"    jnz {short_label}")
            self._emit("    mov rax, 0")
            self._emit(f"    jmp {end_label}")
            self._emit(f"{short_label}:")
            self._emit("    mov rax, 1")
            self._emit(f"{end_label}:")

        self._store_from_reg("rax", instr.dest)

    # ----------------------------------------------------------
    # унарные операции
    # ----------------------------------------------------------

    def _gen_unaryop(self, instr):
        """dest = op operand."""
        self._load_to_reg("rax", instr.operand)

        if instr.op == "-":
            self._emit("    neg rax")
        elif instr.op == "!":
            self._emit("    test rax, rax")
            self._emit("    sete al")
            self._emit("    movzx rax, al")
        else:
            raise ValueError(f"unknown unary op: {instr.op}")

        self._store_from_reg("rax", instr.dest)

    # ----------------------------------------------------------
    # метки и переходы
    # ----------------------------------------------------------

    def _gen_label(self, instr):
        self._emit(f"{instr.name}:")

    def _gen_jump(self, instr):
        self._emit(f"    jmp {instr.label}")

    def _gen_jump_if_false(self, instr):
        """if !cond goto label."""
        self._load_to_reg("rax", instr.cond)
        self._emit("    test rax, rax")
        self._emit(f"    jz {instr.label}")

    # ----------------------------------------------------------
    # вызовы функций
    # ----------------------------------------------------------

    def _gen_call(self, instr):
        """dest = call name(args)."""
        if len(instr.args) > len(ARG_REGISTERS):
            raise ValueError(
                f"too many arguments for {instr.name} (max {len(ARG_REGISTERS)})"
            )

        # кладём аргументы в регистры
        for i, arg in enumerate(instr.args):
            self._load_to_reg(ARG_REGISTERS[i], arg)

        # вызов
        self._emit(f"    call {instr.name}")

        # результат в rax — сохраняем если надо
        if instr.dest is not None:
            self._store_from_reg("rax", instr.dest)